CREATE TABLE CLASS_NUM (
    SCHOOL_CD CHAR(3) NOT NULL,
    CLASS_NUM VARCHAR(5) NOT NULL,
    PRIMARY KEY (SCHOOL_CD, CLASS_NUM)
);

CREATE TABLE SCHOOL (
    SCHOOL_CD CHAR(3) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE STUDENT (
    SCHOOL_CD CHAR(3) NOT NULL,
    NO VARCHAR(10) NOT NULL,
    NAME VARCHAR(10) NOT NULL,
    ENT_YEAR INTEGER NOT NULL,
    CLASS_NUM CHAR(3) NOT NULL,
    IS_ATTEND BOOLEAN NOT NULL,
    PRIMARY KEY (SCHOOL_CD, NO),
    FOREIGN KEY (SCHOOL_CD, CLASS_NUM)
        REFERENCES CLASS_NUM (SCHOOL_CD, CLASS_NUM)
);

CREATE TABLE SUBJECT (
    SCHOOL_CD CHAR(3) NOT NULL,
    CD CHAR(3) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY (SCHOOL_CD, CD)
);

CREATE TABLE TEACHER (
    SCHOOL_CD CHAR(3) NOT NULL,
    ID VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    NAME VARCHAR(10) NOT NULL,
    PRIMARY KEY (SCHOOL_CD, ID)
);

CREATE TABLE TEST (
    SCHOOL_CD CHAR(3) NOT NULL,
    STUDENT_NO VARCHAR(10) NOT NULL,
    SUBJECT_CD CHAR(3) NOT NULL,
    NO INTEGER NOT NULL,
    POINT INTEGER NOT NULL,
    CLASS_NUM VARCHAR(5),
    PRIMARY KEY (SCHOOL_CD, STUDENT_NO, SUBJECT_CD, NO),
    FOREIGN KEY (SCHOOL_CD, STUDENT_NO)
        REFERENCES STUDENT (SCHOOL_CD, NO),
    FOREIGN KEY (SCHOOL_CD, SUBJECT_CD)
        REFERENCES SUBJECT (SCHOOL_CD, CD)
);


INSERT INTO SCHOOL(CD, NAME) VALUES
('tes', 'テスト校');  

INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM) VALUES
('tes', '101'),
('tes', '102'),
('tes', '201'),
('tes', '202');  


INSERT INTO TEACHER(ID, PASSWORD, NAME, SCHOOL_CD) VALUES
('admin1', 'password', '管理者1', 'tes');  


INSERT INTO STUDENT (NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES 
    (124, 'bbb', 2024, 102, FALSE, 'tes'),
    (125, 'ccc', 2025, 201, TRUE, 'tes'),
    (126, 'ddd', 2025, 202, FALSE, 'tes'),
    (127, '大原太郎', 2025, 202, FALSE, 'tes'),
    (128, 'eeee', 2023, 101, TRUE, 'tes'),
    (129, 'ffff', 2023, 102, TRUE, 'tes'),
    (130, 'gggg', 2024, 201, FALSE, 'tes'),
    (131, 'hhhh', 2024, 202, TRUE, 'tes'),
    (132, 'iiii', 2025, 101, FALSE, 'tes'),
    (133, 'jjjj', 2025, 102, TRUE, 'tes'),
    (134, 'kkkk', 2023, 201, FALSE, 'tes'),
    (135, 'llll', 2023, 202, TRUE, 'tes'),
    (136, 'mmmm', 2024, 101, FALSE, 'tes'),
    (137, 'nnnn', 2024, 102, TRUE, 'tes'),
    (138, 'oooo', 2025, 201, FALSE, 'tes'),
    (139, 'pppp', 2025, 202, TRUE, 'tes'),
    (140, 'qqqq', 2023, 101, FALSE, 'tes'),
    (141, 'rrrr', 2023, 102, TRUE, 'tes'),
    (142, 'ssss', 2024, 201, TRUE, 'tes'),
    (143, 'tttt', 2024, 202, FALSE, 'tes');
   